### ISSUE TITLE
Entering special characters into a map entry creates 500 error

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/learningequality.org#344]
When editing a map entry, if there's any special characters entered into the title text box, it produces a 500 error when trying to save. Example: CREE - Instituto Héctor Orlando Gómez Cisneros

![image](https://user-images.githubusercontent.com/22602993/32912564-51997f72-cac4-11e7-8898-3d5233b8ab75.png)

Steps to reproduce: 
Edit one of the map entries and try entering anything other than simple a-z letters.

**Comment by lauradanforth** [comment]
Update: Currently clicking on any map entries to initiate an edit automatically re-directs to the 500 error listed above.

**Comment by dkim0526** [comment]
Hi @lauradanforth, I am trying to reproduce this error. For `editing a map entry`, which page were you at when you were editing the map entries? Is it through [`https://learningequality.org/ka-lite/map/add/` ](https://learningequality.org/ka-lite/map/add/)or  the admin page - `learningequality.org/admin`? Thanks!

**Comment by lauradanforth** [comment]
Hi @dkim0526 ! Thank you! This was through the admin page - learningequality.org/admin and then clicking on Deployment Stories and trying to edit an entry there.

**Comment by dkim0526** [comment]
@lauradanforth Sounds great. I will work on this soon. Thank you for clarifying this!

**Comment by dkim0526** [comment]
Hi @lauradanforth , Could you please check if this issue still exists? Thank you!

**Comment by lauradanforth** [comment]
@dkim0526 I'm still seeing the same 500 error when clicking into an entry to edit it on the admin side.

@indirectlylit When I click onto the map off of http://flestaging.learningequality.org/, it looks the same. Should I see something different (also looks like it redirects to the normal map URL)?

**Comment by indirectlylit** [comment]
@lauradanforth I've been having a lot of trouble reproducing this issue. Would you mind posting the exact steps you're doing and screenshots along the way?

**Comment by lauradanforth** [comment]
@indirectlylit sure - 

1. Log into Admin panel and click on 'Deployment storys'
![image](https://user-images.githubusercontent.com/22602993/40375034-64a88d1a-5db8-11e8-8d25-00d687ba0139.png)
2. Click on the name of an entry to edit it
![image](https://user-images.githubusercontent.com/22602993/40375058-74cbe0d4-5db8-11e8-96e9-b3cfa48d4a7e.png)
3. See 500 error:
![image](https://user-images.githubusercontent.com/22602993/40375079-80820642-5db8-11e8-825e-de5dc26b9bdc.png)

**Comment by lauradanforth** [comment]
Thanks @dkim0526, that makes sense and I see now that it works on http://flestaging.learningequality.org/admin. My apologies for not realizing before that I could access the admin panel on flestaging in addition to the map view. Whoops!

**Comment by indirectlylit** [comment]
awesome!

These changes will be deployed today
