### ISSUE TITLE
docs works locally but not on staging server

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/learningequality.org#352]
Supposed to be handled here: https://github.com/learningequality/learningequality.org/blob/d514c29fc5cf3f2a9b70a797847c7f407009a69c/fle_site/apps/main/urls.py#L25

However on the staging server it doesn't work: http://flestaging.learningequality.org/docs/

Seems like it might be triggering the `ka_lite` `user_guide_detail` view?

**Comment by benjaoming** [comment]
@indirectlylit some layer, maybe in Nginx, redirects to the redirect application, so it's actually 2 redirects... make sure to clear browser cache if testing stuff, because the first is a 301:

```
--2017-12-06 15:29:46--  http://flestaging.learningequality.org/docs/
Resolving flestaging.learningequality.org (flestaging.learningequality.org)... 23.253.32.238
Connecting to flestaging.learningequality.org (flestaging.learningequality.org)|23.253.32.238|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://learningequality.org/r/docs-latest [following]
--2017-12-06 15:29:47--  https://learningequality.org/r/docs-latest
Resolving learningequality.org (learningequality.org)... 104.18.37.151, 104.18.36.151, 2400:cb00:2048:1::6812:2597, ...
Connecting to learningequality.org (learningequality.org)|104.18.37.151|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: http://ka-lite.readthedocs.org/en/latest/ [following]
--2017-12-06 15:29:47--  http://ka-lite.readthedocs.org/en/latest/
Resolving ka-lite.readthedocs.org (ka-lite.readthedocs.org)... 162.209.114.75
```

**Comment by jamalex** [comment]
Works for me.

**Comment by benjaoming** [comment]
Correct link is now http://flestaging.learningequality.org/documentation/

**Comment by indirectlylit** [comment]
yup, I changed the link rather than address that underlying issue
