### ISSUE TITLE
Python version compatibility for PEX can also mention 2.7+ as well

### ISSUE THREAD

**Issue by schiffmanj** [learningequality/learningequality.org#354]
Under the "Linux" section, it says "Compatible with Python 3.4+". This could say "Compatible with Python 2.7+ or 3.4+".

Also, the header should probably say "Linux/OSX".

**Comment by indirectlylit** [comment]
fixed in https://github.com/learningequality/learningequality.org/commit/51ae05e0f882092123726307026fc8e76cab29b3
