### ISSUE TITLE
Need direct link to toolkit README

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/learningequality.org#356]
On the [docs](http://flestaging.learningequality.org/documentation/) page, the link "Start with the overview" points to  https://learningequality.org/r/toolkit-readme which in turn takes you to the drive (same as the link above it)

Maybe this /r/ links should point directly to the PDF?
e.g.  https://drive.google.com/open?id=1lFpQUCb7FPYe7AcMQYMeoM6TQWwR2wot
(obtained by clicking on the PDF and choosing "get sharable link")

**Comment by indirectlylit** [comment]
great catch, thanks! fixed

* https://learningequality.org/r/toolkit
* https://learningequality.org/r/toolkit-readme
