### ISSUE TITLE
update footer text

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/learningequality.org#363]
'join the forums' -> 'join the community forums' ?

cc @lauradanforth @laurenlichtman

**Comment by radinamatic** [comment]
Or simply `join the community`?

**Comment by indirectlylit** [comment]
looks like this is fine:

> ![image](https://user-images.githubusercontent.com/2367265/34023830-d85c21fc-e0fb-11e7-83f1-b9c04a723937.png)

> Or simply join the community?

I was going to do that at first, but it seemed a little ambiguous to me :) it's also already under a 'Community' heading
