### ISSUE TITLE
Typo on BOD bio for Marito Garcia

### ISSUE THREAD

**Issue by jeepurs** [learningequality/learningequality.org#364]
In addition to there being a typo for Marito's bio, he has requested his bio now read as the following:

> Marito Garcia currently serves as Adjunct Faculty and Fellow at Darden School
of Business, University of Virginia and has experience working in 55 countries
during his 18 years at the World Bank where he served as Senior Staff.  While at
the World Bank, Marito served in numerous capacities as Sector and Program
Management roles with work focusing on education, orphans and vulnerable
children, technical-vocational skill development, and early childhood
development in Latin America and Sub-Saharan countries.   He holds a PhD in
Development Economics from the Institute of Social Studies, Erasmus University
Rotterdam, and completed an Executive Program at the Harvard Business
School.

**Comment by indirectlylit** [comment]
updated: http://learningequality.org/about/board/

note - this content is edited from the admin CMS
