### ISSUE TITLE
Reframe language on Kolibri download page for Linux/OSX

### ISSUE THREAD

**Issue by carinediaz** [learningequality/learningequality.org#389]
Please alter language to make it more non-tech user-friendly

**Current language:** 

_Portable offline executable you can run 
if you have Python 2.7+ or 3.4+ installed_

**Suggestion:**
_You can run the portable offline executable if you have Python 2.7+ or 3.4+ installed_

cc @khangmach @indirectlylit @radinamatic @laurenlichtman

**Comment by indirectlylit** [comment]
Context: 

![image](https://user-images.githubusercontent.com/2367265/39495414-0a1dff0c-4d4f-11e8-978c-d4a4217472f0.png)

see also related feedback for Debian here: https://github.com/learningequality/learningequality.org/issues/382#issuecomment-374415122

**Comment by indirectlylit** [comment]
fixed last month in #384
